# Generated by Django 4.2.16 on 2024-12-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
